version: '3'
services:
  spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    container_name: spark-master
    ports:
    - "8080:8080"
    - "7077:7077"
    environment:
    - "ENABLE_INIT_DAEMON=false"
  spark-worker:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker
    depends_on:
    - spark-master
    ports:
    - "8081:8081"
    environment:
    - "SPARK_MASTER=spark://spark-master:7077"
    - "ENABLE_INIT_DAEMON=false"
    deploy:
      replicas: 2
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    image: com.david/spark-windowing-producer:0.1-SNAPSHOT
    depends_on:
      - kafka
    environment:
      - "BROKER_HOST=kafka"
      - "BROKER_PORT=9092"
  spark-consumer:
    image: com.david/spark-windowing-consumer:0.1-SNAPSHOT
    depends_on:
      - kafka
      - spark-master
      - spark-worker
    volumes:
    - /tmp:/tmp
    environment:
    - "ENABLE_INIT_DAEMON=false"
    - "SPARK_MASTER_NAME=spark-master"
    - "SPARK_MASTER_PORT=7077"
    - "SPARK_APPLICATION_ARGS=kafka:9092"

